# Generated by Django 3.2.14 on 2023-04-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_review_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество оценок'),
        ),
    ]
