# Generated by Django 3.2.14 on 2023-04-12 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_teacher_grade_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade_mean',
            field=models.FloatField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Средняя оценка'),
        ),
    ]
